[server]
headless = true
address = "0.0.0.0"
port = 8501
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
textColor = "#262730"
font = "sans serif"
